### ISSUE TITLE
Descontinuidade

### ISSUE THREAD

**Issue by marcosgerene** [samuelrochaoliveira/SPEDBr.NET#43]
Boa noite @samuelrochaoliveira 

Acredito que o Sr. deva remover o aviso de descontinuidade do projeto e cancelar a alteração ou mudar o prazo, pois o outro projeto não está ativo e o prazo já passou, e este tipo de aviso pode inibir novos usuários...

abraços

**Comment by samuelrochaoliveira** [comment]
Olá @marcosgerene boa noite, realmente estive pensando nisso, atualmente a biblioteca não comporta nem 30% do que eu tenho planejado mas acredito que vou continuar a manter essa versão da lib em NET FRAMEWORK e futuramente irei portar com mais calma para o NET STANTARD, apesar das mudanças previstas algumas são bem chatas de tratar, principalmente no caso da certificação digital, o que não é o caso do SPEDBr pois não faz uso de assinatura com certificado ainda.
